apiVersion: v1
kind: Pod
metadata:
  name: wwt-sidecar-debug
spec:
  containers:
    - name: wwt-sidecar
      image: quay.io/ccarson/wwt-sidecar
      securityContext:
        privileged: true
        capabilities:
          add: ["NET_ADMIN", "MKNOD"]
      env:
        - name: VPN_USER
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: username
        - name: VPN_PASS
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: password
        - name: VPN_GROUP
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: group
        - name: VPN_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: endpoint
    - name: debug
      image: fedora:34
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  imagePullSecrets:
    - name: ccarson-bot-pull-secret
